### PR TITLE
Small tweaks

### PR DESCRIPTION
**Pull request by gregelin**
Add test csv file.
Update requirements.txt.
Tweak comments in sample-pipeline.sh.
Update README.md.

### CODE REVIEW

**Review by woodt — APPROVED** [review]

**Review by woodt — CHANGES_REQUESTED** [review]
The requirements file got bumped to pull in spacy 3.0, which has incompatible API changes and doesn't work with ssp.py;  I guess we should pin it to a 2.x version in the `requirements.in`.

IMHO, I'd prefer to use the poetry configuration as the source of truth so we don't have to keep the dependences in two places.

**Comment by gregelin** [comment]
I can go along with using Poetry, but two of us could not get poetry to
work. Do you have a good primer.

Also, what is meant by this bullet point, "- Use the tool `ssp.py` to
convert existing machine readable SSPs into a standard format (e.g., CSV or
JSON-L)"? I thought ssp.py required either a pipe-delimited file of control
statements or csv file of controls statements. When I see "machine readable
SSPs" I think of the entire SSP and also OSCAL. Can you clarify, please?


Greg Elin
CEO, GovReady PBC
p: 917-304-3488
e: gregelin@govready.com

**Comment by gregelin** [comment]
I rewrote


   - Use the tool `ssp.py` to convert existing machine readable SSPs into a
   standard format (e.g., CSV or JSON-L)

to:


   - Convert existing pipe-delimited and csv structured SSP control
   statements into a standard control statement format (e.g., CSV or JSON-L)
   ssp.py.

Is that edit accurate?

Greg Elin
CEO, GovReady PBC
p: 917-304-3488
e: gregelin@govready.com

**Comment by woodt** [comment]
> I can go along with using Poetry, but two of us could not get poetry to work. Do you have a good primer. 

https://python-poetry.org/docs/

I've installed it on Linux, MacOS, and Windows following the instructions there.

**Comment by woodt** [comment]
>  Also, what is meant by this bullet point, "- Use the tool `ssp.py` to convert existing machine readable SSPs into a standard format (e.g., CSV or JSON-L)"? I thought ssp.py required either a pipe-delimited file of control statements or csv file of controls statements. When I see "machine readable SSPs" I think of the entire SSP and also OSCAL. Can you clarify, please? 

ssp.py reads CSV, JSON-L, and "pipe-separated values" and can write those formats.  If you are starting with CSV files, for example, that have control ids and statements scattered among other columns. it is very convenient to convert them to simpler CSV or JSON-L files for subsequent processing (you don't need to remember which columns contain which values.)

ssp.py doesn't read OSCAL.

**Comment by woodt** [comment]
> I rewrote - Use the tool `ssp.py` to convert existing machine readable SSPs into a standard format (e.g., CSV or JSON-L) to: - Convert existing pipe-delimited and csv structured SSP control statements into a standard control statement format (e.g., CSV or JSON-L) ssp.py. Is that edit accurate? Greg Elin CEO, GovReady PBC p: 917-304-3488 e: gregelin@govready.com

Yes, I think that is accurate.

**Pull request merged**
